server:
  port: 8888
  servlet:
    context-path: /dudusam
    session:
      timeout: 30m

spring:
  session:
    jdbc:
      initialize-schema: embedded
      schema: classpath:org/springframework/session/jdbc/public
      table-name: SPRING_SESSION
    store-type: jdbc